name: Repo Downloader

on:
  workflow_dispatch:
    inputs:
      SYNC_URL:
        description: 'SYNC_URL'
        required: true
        default: 'https://github.com/PitchBlackRecoveryProject/manifest_pb'
      MANIFEST_BRANCH:
        description: 'MANIFEST_BRANCH'
        required: true
        default: 'android-12.1'

jobs:
  build:
    if: github.event.repository.owner.id == github.event.sender.id
    runs-on: ubuntu-24.04
    permissions:
      contents: write
    steps:
 
    # You might want to Checkout your repo first, but not mandatory
    - name: Check Out
      uses: actions/checkout@v7

    # Cleanup The Actions Workspace Using Custom Composite Run Actions
    - name: Cleanup
      uses: rokibhasansagar/slimhub_actions@main

    - name: Initialize workspace
      run: |
        mkdir workspace
        cd workspace
        echo "workspace-folder=$(pwd)" >> $GITHUB_OUTPUT
      id: pwd
      
    - name: Prepare the build environment
      run: |
        sudo apt update && sudo apt upgrade -y
        DEBIAN_FRONTEND=noninteractive sudo apt install -yq \
            linux-modules-extra-$(uname -r) \
            git python3 tar aria2
        curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
        chmod a+x ~/bin/repo
        sudo ln -sf ~/bin/repo /usr/bin/repo
      working-directory: ${{ steps.pwd.outputs.workspace-folder }}
      
    - name: Setup SSH Keys
      if: ${{ startsWith(github.event.inputs.SYNC_URL, 'git@github.com') }}
      uses: webfactory/ssh-agent@v0.9.0
      with:
          ssh-private-key: |
            ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Sync OrangeFox sources and minimal manifest
      run: |
        mkdir pbrp
        cd pbrp
        repo init --depth=1 -u ${{ inputs.SYNC_URL }} -b ${{ inputs.MANIFEST_BRANCH }}
        repo sync --force-sync -j$(npoc --all)
      working-directory: ${{ steps.pwd.outputs.workspace-folder }}

    - name: Zip Synced sources
      run: |
        cd ${{ steps.pwd.outputs.workspace-folder }}
        tar -zcv -f ./prbp_${{ github.event.inputs.MANIFEST_BRANCH }}.tar.gz pbrp
    
    - name: Upload Artifact
      uses: actions/upload-artifact@v7
      with:
        name: sync-pbrp
        path: ${{ steps.pwd.outputs.workspace-folder }}/pbrp_${{ github.event.inputs.MANIFEST_BRANCH }}.tar.gz
